app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('clientes.urls')),
    path('', include('configuracoes.urls')),
    path('', include('contratos.urls')),
    path('', include('empresas.urls')),
    path('', include('noticias.urls')),
    path('', include('veiculos.urls')),
    
]

configuracoes/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('cliente/<int:id_cliente>/palavras-chave/', views.ClientePalavrasChaveListView.as_view(), name='cliente_palavras_chave_list'),
    path('cliente/<int:id_cliente>/noticias/', views.ClienteNoticiasListView.as_view(), name='cliente_noticias_list'),
    path('categorias/list/', views.CategoriaListView.as_view(), name='categoria_list'),
    path('categorias/create/', views.CategoriaCreateView.as_view(), name='categoria_create'),
    path('categorias/<int:pk>/detail/', views.CategoriaDetailView.as_view(), name='categoria_detail'),
    path('categorias/<int:pk>/update/', views.CategoriaUpdateView.as_view(), name='categoria_update'),
    path('categorias/<int:pk>/delete/', views.CategoriaDeleteView.as_view(), name='categoria_delete'),
    path('palavras-chave/list/', views.PalavraChaveListView.as_view(), name='palavra_chave_list'),
    path('palavras-chave/create/', views.PalavraChaveCreateView.as_view(), name='palavra_chave_create'),
    path('palavras-chave/<int:pk>/detail/', views.PalavraChaveDetailView.as_view(), name='palavra_chave_detail'),
    path('palavras-chave/<int:pk>/update/', views.PalavraChaveUpdateView.as_view(), name='palavra_chave_update'),
    path('palavras-chave/<int:pk>/delete/', views.PalavraChaveDeleteView.as_view(), name='palavra_chave_delete'),
]

configuracoes/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from clientes.models import ErpCliente, ErpEmpresa
from noticias.models import NoticiaImportada


class Installsistemas(models.Model):
    cd_cliente_sistema = models.IntegerField(
        db_column='CodSys', primary_key=True, verbose_name='Código do Sistema'
    )
    nome_cliente = models.CharField(
        db_column='no_cliente',
        max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Nome do Cliente'
    )
    nome_cliente_sistema = models.CharField(
        db_column='NmoSys', max_length=100,
        db_collation='SQL_Latin1_General_CP1_CI_AS',
        verbose_name='Nome do Sistema'
    )
    ativo_no_sistema = models.BooleanField(
        db_column='ativosys', verbose_name='Ativo no Sistema'
    )
    diretorio_sistema = models.CharField(
        db_column='diretoriosys',
        max_length=25, db_collation='SQL_Latin1_General_CP1_CI_AS',
        verbose_name='Diretório do Sistema'
    )
    cd_modelo_pagina_cliente = models.CharField(
        db_column='cd_modelo',
        max_length=4, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Modelo da Página do Cliente'
    )
    cd_ordenacao = models.CharField(
        max_length=10, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Ordenação'
    )
    tipo_arquivo_preferencial = models.CharField(
        db_column='tp_arquivo_preferencial',
        max_length=3, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Tipo de Arquivo Preferencial'
    )
    nome_imagem_logo = models.CharField(
        db_column='no_imagem_logo',
        max_length=30, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Imagem do Logo'
    )
    cd_senha = models.CharField(
        max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Código da Senha'
    )
    in_bloqueio_site = models.CharField(
        max_length=1, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Bloqueio no Site'
    )
    in_avalia_noticia = models.CharField(
        max_length=1, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Avaliação da Notícia'
    )
    nome_cliente_pagina_sistema = models.CharField(
        db_column='PalavrasSys', max_length=500,
        db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True,
        verbose_name='Nome da Página do Cliente no Sistema'
    )
    nome_grupo_veiculo_ordenado = models.CharField(
        db_column='no_grupo_veiculo_ordenado',
        max_length=40, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Grupo de Veículos Ordenados'
    )
    nome_grupo_veiculo_nao_ordenado = models.CharField(
        db_column='no_grupo_veiculo_nao_ordenado',
        max_length=40, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Grupo de Veículos Não Ordenados'
    )
    nome_grupo_veiculo_coluna = models.CharField(
        db_column='no_grupo_veiculo_coluna',
        max_length=40, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Grupo de Veículos em Coluna'
    )
    in_email_bloqueado = models.CharField(
        max_length=1, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Email Bloqueado'
    )
    id_google_analytics = models.CharField(
        max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='ID do Google Analytics'
    )
    observacao = models.CharField(
        db_column='tt_observacao',
        max_length=2000, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Observações'
    )
    in_site_iis_ok = models.CharField(
        max_length=1, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Site IIS OK'
    )
    in_materia_dia_publicacao = models.CharField(
        max_length=1, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Matéria no Dia de Publicação'
    )
    in_apenas_veiculo_contratado = models.CharField(
        max_length=1, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Apenas Veículo Contratado'
    )
    id_cliente = models.ForeignKey(
        ErpCliente, models.DO_NOTHING, db_column='id_cliente', blank=True, null=True
    )
    tp_sistema = models.CharField(
        max_length=3, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Tipo de Sistema'
    )
    in_apenas_categoria_principal = models.CharField(
        max_length=1, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Apenas Categoria Principal'
    )
    id_contrato = models.IntegerField(
        blank=True, null=True, verbose_name='ID do Contrato'  # FK
    )
    id_proposta = models.IntegerField(
        blank=True, null=True, verbose_name='ID da Proposta'  # FK
    )
    in_exibe_espaco_ocupado = models.CharField(
        max_length=1, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Exibe Espaço Ocupado'
    )
    in_exibe_valoracao = models.CharField(
        max_length=1, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Exibe Valoração'
    )
    in_exibe_avaliacao = models.CharField(
        max_length=1, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Exibe Avaliação'
    )
    cd_empresa = models.ForeignKey(
        ErpEmpresa, models.DO_NOTHING, db_column='cd_empresa'
    )

    dt_ativacao = models.DateTimeField(
        blank=True, null=True, verbose_name='Data de Ativação'
    )
    in_obrigatorio_usuario_senha = models.CharField(
        max_length=1, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Usuário e Senha Obrigatórios'
    )
    in_exibe_logo_noticia = models.CharField(
        max_length=1, db_collation='SQL_Latin1_General_CP1_CI_AS',
        blank=True, null=True, verbose_name='Exibe Logo na Notícia'
    )
    in_incluir_vinheta = models.CharField(
        db_column='In_incluir_vinheta', max_length=1,
        db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True,
        verbose_name='Incluir Vinheta'
    )

    class Meta:
        managed = False
        db_table = 'InstallSistemas'
        verbose_name_plural = 'Configurações do Cliente'

        def __str__(self):
            return self.no_cliente


class Categoriapalavrachave(models.Model):
    nome = models.CharField(unique=True, max_length=255,
                            db_collation='SQL_Latin1_General_CP1_CI_AS')

    class Meta:
        managed = False
        db_table = 'CategoriaPalavraChave'

    def __str__(self):
        return self.nome


class Palavrachave(models.Model):
    id_cliente = models.ForeignKey(
        ErpCliente, models.DO_NOTHING, db_column='id_cliente')
    id_categoria = models.ForeignKey(
        Categoriapalavrachave, models.DO_NOTHING, db_column='id_categoria')
    palavra = models.CharField(
        max_length=255, db_collation='SQL_Latin1_General_CP1_CI_AS')
    data_cadastro = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'PalavraChave'
        unique_together = (('id_cliente', 'palavra'),)

    def __str__(self):
        return self.palavra

configuracoes/views.py
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from .models import Categoriapalavrachave, Palavrachave
from .forms import CategoriaPalavraChaveForm, PalavraChaveForm
from clientes.models import ErpCliente
from noticias.models import NoticiaImportada

# view para as PC do cliente


class ClientePalavrasChaveListView(ListView):
    model = Categoriapalavrachave
    template_name = 'cliente_palavra_chave_list.html'
    context_object_name = 'categorias'

    def get_queryset(self):
        """
        Filtra as categorias de palavras-chave do cliente selecionado.
        """
        id_cliente = self.kwargs.get(
            'id_cliente')  # 🔹 Alterado para "id_cliente"
        self.cliente = get_object_or_404(ErpCliente, id_cliente=id_cliente)
        return Categoriapalavrachave.objects.filter(palavrachave__id_cliente=self.cliente).distinct()

    def get_context_data(self, **kwargs):
        # pega o cliente e adiciona ao contexto
        context = super().get_context_data(**kwargs)
        context['cliente'] = self.cliente
        return context

# view para as notícias do cliente
# class ClienteNoticiasListView(ListView):
#     model = NoticiaImportada
#     template_name = 'cliente_noticias_list.html'  
#     context_object_name = 'noticias'
#     paginate_by = 20  

#     def get_queryset(self):
#         id_cliente = self.kwargs.get('id_cliente')
#         return NoticiaImportada.objects.filter(
#             clientes_relacionados__contains=str(id_cliente)
#         ).order_by('-dt_noticia')

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         id_cliente = self.kwargs.get('id_cliente')
#         cliente = get_object_or_404(ErpCliente, id_cliente=id_cliente)
#         noticias = self.get_queryset()

#         # Mapeamento de tipos de veículos
#         tipos_veiculo_mapeados = {
#             'Impresso': 'Impresso',
#             'Jornal': 'Impresso',
#             'Revista': 'Revista',
#             'Site': 'Site',
#             'Portal': 'Site',
#             'Blog': 'Blog',
#             'Podcast': 'Podcast',
#             'Rádio': 'Rádio',
#             'Televisão': 'Televisão',
#             'Videocast': 'Videocast'
#         }

#         # Dicionário para agrupar as notícias
#         noticias_por_tipo = {tipo: [] for tipo in tipos_veiculo_mapeados.values()}

#         for noticia in noticias:
#             if noticia.cd_veiculo and noticia.cd_veiculo.tipo_veiculo:
#                 tipo_veiculo = noticia.cd_veiculo.tipo_veiculo.descricao_tipo_veiculo
#                 print(f"Tipo de veículo retornado do banco: {tipo_veiculo}")  

#                 tipo_veiculo = tipos_veiculo_mapeados.get(tipo_veiculo, 'Outros')

#                 if tipo_veiculo not in noticias_por_tipo:
#                     noticias_por_tipo[tipo_veiculo] = []
#                 noticias_por_tipo[tipo_veiculo].append(noticia)

#         context['cliente'] = cliente
#         context['noticias_por_tipo'] = noticias_por_tipo
#         return context

class ClienteNoticiasListView(ListView):
    model = NoticiaImportada
    template_name = 'cliente_noticias_list.html'  
    context_object_name = 'noticias'
    paginate_by = 20  

    def get_queryset(self):
        id_cliente = self.kwargs.get('id_cliente')
        return NoticiaImportada.objects.filter(
            clientes_relacionados__contains=str(id_cliente)
        ).order_by('-dt_noticia')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        id_cliente = self.kwargs.get('id_cliente')
        cliente = get_object_or_404(ErpCliente, id_cliente=id_cliente)
        noticias = self.get_queryset()

        # Criar um dicionário para armazenar todas as notícias agrupadas corretamente
        noticias_por_tipo = {}

        for noticia in noticias:
            if noticia.cd_veiculo and noticia.cd_veiculo.tipo_veiculo:
                tipo_veiculo = noticia.cd_veiculo.tipo_veiculo.descricao_tipo_veiculo.strip()  
                # print(f"Tipo de veículo retornado do banco: {tipo_veiculo}")  

                # Adicionar o tipo de veículo ao dicionário caso não exista
                if tipo_veiculo not in noticias_por_tipo:
                    noticias_por_tipo[tipo_veiculo] = []

                noticias_por_tipo[tipo_veiculo].append(noticia)

        # Ordenar as categorias pelo nome
        noticias_por_tipo = dict(sorted(noticias_por_tipo.items()))

        context['cliente'] = cliente
        context['noticias_por_tipo'] = noticias_por_tipo
        return context



class CategoriaListView(ListView):
    model = Categoriapalavrachave
    template_name = 'categoria_list.html'
    context_object_name = 'categorias'
    paginate_by = 10  # Paginação para 10 categorias por página

# 🔷 Criar uma nova categoria


class CategoriaCreateView(CreateView):
    model = Categoriapalavrachave
    template_name = 'categoria_create.html'
    form_class = CategoriaPalavraChaveForm
    success_url = reverse_lazy('categoria_list')

# 🔷 Visualizar detalhes de uma categoria


class CategoriaDetailView(DetailView):
    model = Categoriapalavrachave
    template_name = 'categoria_detail.html'
    context_object_name = 'categoria'

# 🔷 Atualizar uma categoria existente


class CategoriaUpdateView(UpdateView):
    model = Categoriapalavrachave
    template_name = 'categoria_update.html'
    form_class = CategoriaPalavraChaveForm
    success_url = reverse_lazy('categoria_list')

# 🔷 Excluir uma categoria


class CategoriaDeleteView(DeleteView):
    model = Categoriapalavrachave
    template_name = 'categoria_delete.html'
    success_url = reverse_lazy('categoria_list')

# 🔷 Listar palavras-chave de um cliente específico


class PalavraChaveListView(ListView):
    model = Palavrachave
    template_name = 'palavra_chave_list.html'
    context_object_name = 'palavras'
    paginate_by = 20  # Paginação para 20 palavras-chave por página

    def get_queryset(self):
        """
        Filtra as palavras-chave pelo cliente logado.
        """
        queryset = super().get_queryset()
        return queryset.filter(id_cliente=self.request.user.erpcliente)

# 🔷 Criar uma nova palavra-chave


class PalavraChaveCreateView(CreateView):
    model = Palavrachave
    template_name = 'palavra_chave_create.html'
    form_class = PalavraChaveForm
    success_url = reverse_lazy('palavra_chave_list')

# 🔷 Visualizar detalhes de uma palavra-chave


class PalavraChaveDetailView(DetailView):
    model = Palavrachave
    template_name = 'palavra_chave_detail.html'
    context_object_name = 'palavra'

# 🔷 Atualizar uma palavra-chave existente


class PalavraChaveUpdateView(UpdateView):
    model = Palavrachave
    template_name = 'palavra_chave_update.html'
    form_class = PalavraChaveForm

    def form_valid(self, form):
        """
        Salva o formulário e redireciona para a página de detalhes da palavra-chave.
        """
        self.object = form.save()
        return HttpResponseRedirect(reverse('palavra_chave_detail', kwargs={'pk': self.object.pk}))

# Excluir uma palavra-chave


class PalavraChaveDeleteView(DeleteView):
    model = Palavrachave
    template_name = 'palavra_chave_delete.html'
    success_url = reverse_lazy('palavra_chave_list')

configuracoes/templates/cliente_noticias_list.html
{% extends 'base.html' %}

{% block title %}
SMM - Notícias do Cliente
{% endblock %}

{% block content %}
<div class="container mt-4">
    <h3 class="display-6">Notícias Vinculadas para <strong>{{ cliente.nome_cliente }}</strong></h3>

    <!-- Filtros -->
    <form method="get" action="{% url 'cliente_noticias_list' cliente.id_cliente %}">
        <div class="row mb-3">
            <div class="col-md-4">
                <label for="titulo" class="form-label">Título</label>
                <input type="text" name="titulo" id="titulo" class="form-control" placeholder="Buscar título" value="{{ request.GET.titulo }}">
            </div>
            <div class="col-md-4">
                <label for="conteudo" class="form-label">Conteúdo</label>
                <input type="text" name="conteudo" id="conteudo" class="form-control" placeholder="Buscar conteúdo" value="{{ request.GET.conteudo }}">
            </div>
            <div class="col-md-4 d-flex align-items-end">
                <button type="submit" class="btn btn-outline-primary">Buscar</button>
            </div>
        </div>
    </form>

    <!-- Organização por Tipo de Veículo -->
    {% for tipo, noticias_tipo in noticias_por_tipo.items %}
        {% if noticias_tipo %}
            <div class="accordion mb-3" id="accordion-{{ tipo }}">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="heading-{{ tipo }}">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{ tipo }}" aria-expanded="false" aria-controls="collapse-{{ tipo }}">
                            {{ tipo }} ({{ noticias_tipo|length }} notícias)
                        </button>
                    </h2>
                    <div id="collapse-{{ tipo }}" class="accordion-collapse collapse" aria-labelledby="heading-{{ tipo }}" data-bs-parent="#accordion-{{ tipo }}">
                        <div class="accordion-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-hover">
                                    <thead class="table-dark">
                                        <tr>
                                            <th>Ações</th>
                                            <th>Título</th>
                                            <th>Data de Publicação</th>
                                            <th>Data de Importação</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for noticia in noticias_tipo %}
                                            <tr>
                                                <td>
                                                    <a href="{{ noticia.ds_url }}" target="_blank" class="btn btn-info btn-sm p-1" title="Visualizar">
                                                        <i class="bi bi-eye"></i>
                                                    </a>
                                                </td>
                                                <td>{{ noticia.titulo }}</td>
                                                <td>{{ noticia.dt_noticia|date:"d/m/Y" }}</td>
                                                <td>{{ noticia.dt_importacao|date:"d/m/Y" }}</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
    {% empty %}
    <p class="text-center">Nenhuma notícia vinculada encontrada.</p>
    {% endfor %}

    <!-- Paginação -->
    {% include 'components/_pagination.html' %}
</div>
{% endblock %}

configuracoes/templates/cliente_palavra_chave_list.html
{% extends 'base.html' %}

{% block title %}
SMM - Palavras-chave do Cliente
{% endblock %}

{% block content %}
<div class="container mt-4">
    <h3 class="display-6">Palavras-chave de {{ cliente.nome_cliente }}</h3>

    <div class="row">
        <!-- Listagem de Categorias e Palavras-Chave -->
        <div class="col-md-12">
            {% for categoria in categorias %}
            <div class="card mb-3">
                <div class="card-header bg-primary text-white">
                    <strong>{{ categoria.nome }}</strong>
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        {% for palavra in categoria.palavrachave_set.all %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            {{ palavra.palavra }}
                            <span class="badge bg-secondary">Cliente: {{ palavra.id_cliente.nome_cliente }}</span>
                        </li>
                        {% empty %}
                        <p class="text-muted">Nenhuma palavra-chave cadastrada nesta categoria.</p>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% empty %}
            <p class="text-center">Nenhuma categoria cadastrada para este cliente.</p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}